### ISSUE TITLE
Error when setting "epa_wpa = TRUE" in cfbd_pbp_data() 

### ISSUE THREAD

**Issue by montgomeryinman** [sportsdataverse/cfbfastR#103]
I receive this error when setting epa_wpa = TRUE in cfbd_pbp_data() :

<img width="500" alt="Screenshot 2024-08-27 at 2 55 09 PM" src="https://github.com/user-attachments/assets/26c103e3-e8b8-440a-8f2c-0bcd708f2afe">

I am able to run cfbd_pbp_data()  by setting epa_wpa = FALSE (returns 56 columns and no epa/wpa data).

**Comment by akeaswaran** [comment]
Based on that error message, it seems like the method header for `stringi::stri_extract_first_regex()` may have changed -- what versions of R, cfbfastR, and stringi are you using?

**Comment by montgomeryinman** [comment]
This is resolved now, thanks! 
It was the classic problem of not having the updated versions of cfbfastR and/or stringi.

If anyone has the same problem I was using:
R version: 4.2.1 
cfbfastR: 1.9.0 (_1.9.5 is the latest as of now_)
stringi: 1.8.2 (_1.8.3 is the latest_)

**Comment by montgomeryinman** [comment]
This is resolved now, thanks! 
It was the classic problem of not having the updated versions of cfbfastR and/or stringi.

If anyone has the same problem I was using:
R version: 4.2.1 
cfbfastR: 1.9.0 (_1.9.5 is the latest as of now_)
stringi: 1.8.2 (_1.8.3 is the latest_)
