### ISSUE TITLE
EPA on Punt plays looks broken

### ISSUE THREAD

**Issue by rebinion** [sportsdataverse/cfbfastR#65]
**Describe the bug**
The EPA on punt plays does not seem to be factoring correctly. 

**To Reproduce**
1. Go to the play by play data
2. Filter play_type == "Punt"
3. Observe how many punt plays include very large EPA numbers for the defensive team on uneventful plays

**Expected behavior**
For punt plays that net out to around 40 yards, the EPA should be minimal. 

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Kazink36** [comment]
This should be working properly as of cfbfastR 1.9.0

Feel free to reopen if you still see any funky results.
