### ISSUE TITLE
cfbd_game_player_stats columns are lists instead of numeric

### ISSUE THREAD

**Issue by JerrickBackous** [sportsdataverse/cfbfastR#84]
**Describe the bug**
When using the cfbd_game_player_stats() function the stat columns should be numeric and the data should be wide, referenced here https://cfbfastr.sportsdataverse.org/reference/cfbd_game_player_stats.html, but the columns import as lists and the category column is still present.

**To Reproduce**
Run the following code: cfbd_game_player_stats(2013, week = 1, team = "Florida State", category = "passing")

**Expected behavior**
The data is wider and the stat columns are numeric instead of lists.
![image](https://user-images.githubusercontent.com/77847817/198695286-4aba8e0a-91ec-42ff-9252-08d0b127977e.png)

**Screenshots**
I used the vignette examples to show the actual output below:
![image](https://user-images.githubusercontent.com/77847817/198694263-f408c58a-6f07-48ed-8135-baecd74cd4a3.png)
![image](https://user-images.githubusercontent.com/77847817/198694381-d6c90aeb-c926-403a-a39b-0ff5cb205ea5.png)

**Desktop (please complete the following information):**
 - OS: Windows 11

**Comment by akeaswaran** [comment]
IIRC a similar issue was fixed in #75 -- are you sure you're on the most up-to-date version?

**Comment by JerrickBackous** [comment]
That was the issue! I was using the 1.9.0 CRAN version. After updating to 1.9.3 GitHub version the issue was solved. Thanks!
