### ISSUE TITLE
cfbd_betting_lines

### ISSUE THREAD

**Issue by ryanmamitchell** [sportsdataverse/cfbfastR#93]
In cfbfastR_1.9.0 it only loads certain years of betting data, for example, 2019-2022 but not 2023.  However when cross-referenced with the cfbdata website, the betting data can be found there. I also attempted running the code while directly referencing the package (cfbfastR::), as per a previous closed bug report, but to no avail.

**To Reproduce**
1. bet_data <- cfbd_betting_lines(year = 2023)
2. also attempted: bet_i <- cfbfastR::cfbd_betting_lines(year = i)
3. Error: 2023-11-07 20:13:31: Invalid arguments or no betting lines data available!

**Expected behavior**
Should return my dataset named bet_data containing the betting lines data frame

**Desktop (please complete the following information):**
 - OS: iOS
 - Browser: Chrome

**Comment by Tickkid** [comment]
> In cfbfastR_1.9.0 it only loads certain years of betting data, for example, 2019-2022 but not 2023. However when cross-referenced with the cfbdata website, the betting data can be found there. I also attempted running the code while directly referencing the package (cfbfastR::), as per a previous closed bug report, but to no avail.
> 
> **To Reproduce**
> 
> 1. bet_data <- cfbd_betting_lines(year = 2023)
> 2. also attempted: bet_i <- cfbfastR::cfbd_betting_lines(year = i)
> 3. Error: 2023-11-07 20:13:31: Invalid arguments or no betting lines data available!
> 
> **Expected behavior** Should return my dataset named bet_data containing the betting lines data frame
> 
> **Desktop (please complete the following information):**
> 
> * OS: iOS
> * Browser: Chrome

Having same issue on OS: Windows using RStudio 2023.09.1 Build 494 and R version 4.3.2

**Comment by Haddon-Sandefur** [comment]
Also having this issue. Currently using R version 4.3.1 and RStudio 524

**Comment by akeaswaran** [comment]
Hi all: 

Looks like CFBData returns a NaN for an FCS betting line and cfbfastR doesn't parse that properly. We've let CFBData's maintainers know about that data issue and are working on a fix in cfbfastR to handle edge cases like this better in the future.

Thanks for flagging this!

**Comment by Haddon-Sandefur** [comment]
> Hi all:
> 
> Looks like CFBData returns a NaN for a FCS betting line in 2023 and cfbfastR doesn't parse that properly. We've let CFBData's maintainers know about that data issue and are working on a fix in cfbfastR to handle edge cases like this better in the future.
> 
> Thanks for flagging this!

Awesome, thank you!
