### ISSUE TITLE
cfb_pbp_data() only returning 56 variables

### ISSUE THREAD

**Issue by garbage-time** [sportsdataverse/cfbfastR#95]
I was reading over the [documentation](https://cfbfastr.sportsdataverse.org/reference/cfbd_pbp_data.html) for the `cfb_pbp_data()` function and noticed that it's supposed to return 351 variables. However, upon using it, I only obtain 56 columns for the year 2023 (additional testing in prior years 2020 and 2018 provided the same result.)

I am using:
* `cfbfastR` version 1.9.0
* R version 4.3.1

#### Screenshot of using `glimpse()` on the 2023  `cfb_pbp_data()`  data.
![cfbd_pbp_data_load](https://github.com/sportsdataverse/cfbfastR/assets/99365857/f7cf088d-8bc2-4312-b72e-6045edfe6cee)

I apologize if this is the result of me missing an argument somewhere! Thank you!

**Comment by akeaswaran** [comment]
I've just taken a look at this -- you'll get the full set of 300+ columns if you set `epa_wpa` to TRUE.

**Comment by garbage-time** [comment]
Ah I see! That did the trick. My apologies for not attempting that sooner. Thanks!
