### ISSUE TITLE
Getting CFB team logos without cfbplotR package

### ISSUE THREAD

**Issue by jacole3** [sportsdataverse/cfbfastR#99]
To my knowledge, the geom_cfb_logos package used to only be available in the cfbplotR package (see this post for more: https://kazink36.github.io/cfbplotR/reference/geom_cfb_logos.html). However, I recently upgraded my RStudio to Version 2023.12.1+402, which was released on 1/29/2024 (https://posit.co/download/rstudio-desktop/).

Now, when I attempt to run install.packages("cfbplotR"), I see the following: 

_Warning in install.packages :
package ‘cfbplotR’ is not available for this version of R_

As a result, if I wanted to incorporate college football team logos into a ggplot, is it necessary to uninstall this most recent version of RStudio? Or is there another package, whether that means cfbfastR or something else, that allows us to do the trick?

Thanks in advance for any assistance, and thanks to the cfbfastR team's hard work in general for helping out the football analytics community so thoroughly.

**Comment by saiemgilani** [comment]
Run the following code in a fresh R session

```r
install.packages("remotes")
remotes::install_github("sportsdataverse/cfbfastR")
remotes::install_github("sportsdataverse/cfbplotR")
```

Restart your R session and you should be good to go

**Comment by akeaswaran** [comment]
Closing since this looks resolved.
